#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# core packages
cookbook 'chef-client'
cookbook 'apt'
cookbook 'chef-solo-search', '>= 0.4.0', :git => "https://github.com/edelight/chef-solo-search"
cookbook 'build-essential', '>= 1.4.0'

#system packages
cookbook 'vim', '>= 1.0.2'
cookbook 'ntp', '>= 1.3.2'
cookbook 'openssh', '>= 1.2.0'
cookbook 'git', '>=2.5.2'
cookbook 'users', '>= 1.5.0'
cookbook 'ssh_known_hosts', '>= 1.0.0'

# cookbook 'apache2', '>= 1.0.0' # We have to use our modified version for 2.4
cookbook 'php', '>= 1.2.2'
cookbook 'mysql' , '>= 3.0.2'
cookbook 'percona', '>= 0.14.5'

cookbook 'chef-php', '>= 1.2.0', :git => "https://github.com/priestjim/chef-php"
cookbook 'imagemagick', '>= 0.2.2'

cookbook 'chef-duo-unix', '>= 0.1.0', :git => 'https://github.com/hungtruong/chef-duo-unix.git'
